baseURL: https://mmhshayer.github.io/
languageCode: en-us
title: MMHShayer's Blog
theme: "PaperMod"
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-X3BSZMWKDQ

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: MMHShayer's Blog
  description: "Personal blog & portfolio website."
  keywords: [Blog, Portfolio, PaperMod]
  author: Mohammad Mustakim Hassan
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-icon-57x57.png"
    safari_pinned_tab: "/apple-icon-precomposed.png"

  label:
    text: "\U000100cf"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Welcome to my knowledge vault!
    subtitle: "I am Mohammad Mustakim Hassan. This blog curates my study notes, documents experiments, explores projects and more (to come)!"
    imageUrl: "https://media.giphy.com/media/3ov9jDblR6W2d6NfJC/giphy.gif"
    imageWidth: 120
    imageHeight: 120
    imageTitle: hero sticker
    buttons:
      - name: About me
        url: about
      - name: Archive
        url: archives
    #   - name: Tags
    #     url: tags

  # home-info mode
  homeInfoParams:
    Title: "Welcome to my knowledge vault!"
    Content: >
        - I am Mohammad Mustakim Hassan

        - This blog curates my study notes, documents experiments, explores projects and more (to come) !
  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/viceroyshayer/"
    - name: github
      url: "https://github.com/mmhshayer"
    # - name: kaggle
    #   url: "https://www.kaggle.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  outputs:
      home:
          - HTML
          - RSS
          - JSON # is necessary

  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: "\U0001F50D"
      url: /search/
      weight: 10
    - identifier: archive
      name: archive
      url: /archives/
      weight: 20
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 30
    - identifier: tags
      name: tags
      url: /tags/
      weight: 40
#     # - identifier: example
#     #   name: example.org
#     #   url: https://example.org
#     #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai